### ISSUE TITLE
Suggested changes to the schedule

### ISSUE THREAD

**Issue by karenword** [carpentries/instructor-training#1100]
Submitted by @iswimlikeafish originally as a PR: 

"I would recommend switching Day two's morning and afternoon sessions, or even moving Day two's afternoon session to Day one's morning session. That way we're ending with teaching/feedback as opposed to an introduction of what carpentries are."

**Comment by brownsarahm** [comment]
I've taught with day two switched around twice with @DanielleQuinn (who I think has taught that way with others as well). It worked really well. It also flows nicely to move directly from the homework review and day 2 morning welcome. Splitting the live coding practice to before and after lunch I think is also appreciated by people who want to tinker or practice a little extra before the second time. 

13- Welcome Back (with recap & questions exercise)
20 - Checkout Process
21- How We Operate
Break
14 - Live Coding is a Skill
15 - Preparing to Teach
Lunch
17 - More Practice Live Coding
18 - Managing a Diverse Classroom
Break
23 - Workshop Introductions
24 - Putting it Together
Wrap Up

**Comment by ChristinaLK** [comment]
I think you can teach Day 2 in pretty much any order, so I'm open to a more formal change. I've definitely done live coding before/after lunch so people are doing something fun during the lull of the afternoon post-lunch.

**Comment by karenword** [comment]
I think this is something worth looking at during our next update, as I'm hesitant to make a major structural change between releases. Perhaps we can discuss options for experimenting with the order of episodes when teaching at a Trainer meeting sometime in the mean time? There will be other changes coming along to Day 2 content with that update, and those changes may influence the optimal order of episodes as well.

**Comment by ChristinaLK** [comment]
I think adding this as an announcement at a trainer's meeting makes sense -- letting people know they can try a different order if they want.

**Comment by arieldeardorff** [comment]
Jumping on this issue to say that @jcoliver and I were reflecting today (while we were teaching a workshop) and thought that the afternoon of the second day might flow better to start with How we Operate and then get even more specific and talk about the checkout process. Some folks need that background on the organization and how it works before they can see how the checkout process fits in. I have flipped this for workshops in the past and it seemed to go a little smoother. I don't mind having it the second half of the day but I think the flipped pair could also fit at the beginning of the day as in the suggestion above.

**Comment by vanilink** [comment]
While attending a recent (online) instructor workshop, I felt similarly about the second day's afternoon session. 
In particular with regards to the part where introductions are practiced: 

15:25 | 23. Workshop Introductions | How do you actually start a workshop?

Overall, I quite like that we practice these introductions since this is something I may have overlooked in preparing for a workshop. However, I may suggest to do this exercise towards the beginning of the instructor training (e. g. morning of day 1) as it is equally a way to get to know your fellow learners during the instructor training and in a way can serve as an icebreaker exercise. I would have loved to hear all the different motivations and inspiring stories that people shared right at the beginning. 

I shared this feedback in the workshop itself and several other learners strongly agreed with me which is why I am bringing this issue forward here.
