### ISSUE TITLE
Connect "What is a workshop" to the information on our website

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#1103]
On the [What is a workshop](https://carpentries.github.io/instructor-training/21-carpentries/index.html) section, a lot of the information repeats what is on [The Carpentries Workshops page](https://static.carpentries.org/workshops/).  I think that the instructor training section should refer to the Carpentries Workshops page rather than try to repeat it, as this will make it difficult to keep consistent.  Even now there is information that is inaccurate.

@sheraaronhurt @karenword  what do you think?

**Comment by sheraaronhurt** [comment]
@maneesha  I agree. The Carpentries Workshop page is updated most frequently and will allow for us to only have to update in one place.

**Comment by karenword** [comment]
@maneesha since the [Carpentries.org page](https://carpentries.org/workshops/) is long and rather dense, I'm thinking about a solution that would involve linking to the subheaders on that page (e.g. "What are the requirements for a Carpentries workshop?") but I can't figure out how to do that. Is this possible on our website pages, as it is in the Handbook?

**Comment by karenword** [comment]
Whoops! nevermind -- turns out there are internal links on the page itself 🙃
