### ISSUE TITLE
Include Core Team on Carpentries Roles worksheet

### ISSUE THREAD

**Issue by maneesha** [carpentries/instructor-training#1105]
I think this will help new community members understand what the Core Team does.

**Comment by karenword** [comment]
This worksheet needs updating in several ways now (Community Facilitators!) and it we could also use a fillable version.

FWIW I tried implementing a smaller version of it as a google form in my last training and... it kind of worked? Probably not an optimal solution but:
https://docs.google.com/forms/d/12edxdQ3G28npIBef5KCxjMUjZHbacWAdtGzTvcbU5Qc/edit?usp=sharing

**Comment by Denubis** [comment]
Is it worth me making a LaTeX version that's more maintainable?

**Comment by brownsarahm** [comment]
I would like that.

**Comment by mikemhenry** [comment]
Feedback facilitators too!

**Comment by Denubis** [comment]
Ok, let me see what I can do

**Comment by Denubis** [comment]
@mikemhenry What do they do in 15 words or less?

**Comment by Denubis** [comment]
Quick proof of concept

https://www.overleaf.com/read/svyjzwrpgmnm
[Carpentries_Roles_Quiz.pdf](https://github.com/carpentries/instructor-training/files/5551482/Carpentries_Roles_Quiz.pdf)

**Comment by brownsarahm** [comment]
maybe un-nest the last two to make it space to answer them separately?

**Comment by Denubis** [comment]
[Carpentries_Roles_Quiz (1).pdf](https://github.com/carpentries/instructor-training/files/5557343/Carpentries_Roles_Quiz.1.pdf)

@brownsarahm happy to share edit access of the TeX. I've tried to keep the file trivial so it can be maintained by everyone, but holy expert awareness gap, batman.

**Comment by brownsarahm** [comment]
Would it make sense to add it to this repo for version control here? 

(though then the tex environment needs to be managed, etc)

**Comment by Denubis** [comment]
So from a "technically correct" point of view, we can add it as a submodule to this repo -- but since submodules are even more tricky to get right and non-github ones don't have the github affordances it would mostly be technical performance.

I think the first question is: is the `main.tex` file sufficiently legible to be editable causally? the problem is that I could probably pandocise this whole thing, but that just adds another layer to the tower of complexity. I know R has a tinyTeX compiler, so maybe we should head in that direction?

**Comment by Denubis** [comment]
Ok -- I've moved the TeX into RStudio.cloud and it compiles just fine. Since we already have an R-based infrastructure requirement, the final question is how you would like me to move that r-project into this repo, assuming you're all happy with the quiz?
