### ISSUE TITLE
Learner Profiles and Bias + Stereotypes

### ISSUE THREAD

**Issue by arieldeardorff** [carpentries/instructor-training#1163]
I wanted to pass on feedback from two trainees on the learner profiles section of [learning to teach](https://carpentries.github.io/instructor-training/15-lesson-study/index.html):

One trainee shared that she uses user profiles a lot for user experience testing and that it is really important to think carefully about the bias and stereotypes that you might be encoding in your learner profiles. I am not sure how to avoid this but I definitely think it is worth mentioning in the lesson and if anyone has any strategies for this I would appreciate it.

Another trainee mentioned that they were a little uncomfortable with the cartoons used for the [software carpentry profiles ](https://software-carpentry.org/audience/) and after looking at them again I could see how they might be trending towards caricatures. Maybe we could use images here instead? A site like [pexel](https://www.pexels.com/) could be a place to look for free CC0 images of diverse researchers. 

Adding @jt14den in case he has any additional points.

**Comment by junfu2020** [comment]
Ariel, I definitely echo with you on this. When I went through the instructor training as a trainee, I was having some difficulty in understanding the essential benefits of developing learner profiles. As specified, the intended objective was to help trainees to know who they are teaching the content to. However, at the end of the day, there can be a diverse pool of learners across different skill levels, educational backgrounds etc. There could be literally countless combinations of different characteristics, all of which will lead to many different learner profiles. In the instructor training session, all of us (the trainees) ended up developing a large set of learner profiles. What are the essential takeaways or usefulness for seeing all of the different learner profiles? The other question I had during the practice was the issue of potential implicit biases. When developing a learner profile, I as a trainee could only formulate the conceptualization based on my personal experiences, therefore, there could be potential personal biases involved (such as describing gender, field, background). I hope this section could be somehow tailored into alternative ways, to better overcome or even help trainees to recognize their potential biases in the process. For example, instead of developing learner profiles, how about: asking trainee A to come up with a list of different educational backgrounds of potential learners who may find the lessons useful; asking trainee B to come up with a list of potential career tracks of learners; etc. This way, this lesson may better address the inclusivity issue, and also trainees can perhaps freely combine all of these different descriptors they come up with, and realize there will be so many potential learners (across different backgrounds) who may be the participants of workshops/lessons.

**Comment by ChristinaLK** [comment]
I'll add that the last two times I've taught, I've skipped this section, but mainly because I find it most useful in the context of developing *new* lessons and I teach instructor training with a greater focus on teaching from current lessons. 

I do think it's a useful tool when starting to write a lesson/talk from scratch because (if done well) it puts the instructor in the learner's shoes and can be a lens to consider their motivations, backgrounds, and circumstances. Which nicely aligns with the critiques here, which are expressing concerns about the profiles limiting how we see learners, rather than expanding our view. 

I would maybe consider making this an optional exercise and/or more explicitly stating that the goal of "profiles" is for us to incorporate a learner's perspective in our lesson design and so we need to be intentional in including as many dimensions of the learners as we can. I also like @junfu2020 's suggestion of brainstorming different learner qualities as an alternative to generating concrete profiles.

**Comment by brownsarahm** [comment]
When I do this activity, I try to offer some feedback on the profiles, in the sense of reflecting on how attributes that are listed actually influence teaching. I like the idea of brainstorming qualities and how think it creates an opportunity for more connection to the lesson's objective of preparing to teach. Maybe we could do the lists instead of full profiles (also, lists are faster to write than sentences) and formalize some reflection/evaluation of the qualities that are brought up.  

We could address some throughout the rest of this episode in preparing.  Then return to the unaddressed items on the list in the exercises in Managing a diverse classroom. 

Tying ideas and exercises together more explicitly should help deepen trainees understanding & a more dense set of connections across ideas should also make retention easier. It will require a lot of reminders to trainers to have more interdependence in the episodes, but it could be useful.  We get a lot of feedback that there is an overwhelming amount of information, so more ways to draw connections, should help people chunk it together.

**Comment by brownsarahm** [comment]
Last week, I did this exercise as a few questions instead of having them write full profiles.  Trainees mostly described the breadth of attendees they expect, which might actually better than focusing on a single person for the purpose of preparing. I included a question about what they might need to do to adapt to something as well and got more insight and prompted more open disucssion. 

(when the etherpad is back up, i'll add the exact questions I asked)
