### ISSUE TITLE
create lesson "style guide"

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries/instructor-training#1169]
From PR #1167 

Create a lesson "style guide" with fonts used in images, or other very lesson specific style info. Also include a link to the main Carpentries style guide, if that's still a thing?

This may apply to `styles` also?

**Comment by brownsarahm** [comment]
Mostly we should link to this: https://docs.carpentries.org/topic_folders/communications/resources/style-guide.html

and also [lesson example](https://carpentries.github.io/lesson-example/06-style-guide/index.html). 

Maybe for disambiguation, we call what we want to record in this repo, "maintainer notes"?

**Comment by ChristinaLK** [comment]
I was wondering if there is a convention for this. Does this type of information normally go into CONTRIBUTING? or is there another standard format?

+1 to both suggested links!

**Comment by brownsarahm** [comment]
that's a really good question, I don't know and i'm not even sure who might be good to ask?

**Comment by ACharbonneau** [comment]
There are lots of template ones, but I don't have strong opinions about any of them. My more useful contribution here is that if we set up a `.github` repo in the Carpentries space, you can make a single template there that will propagate across all the repos (you can do the same for COCs and a few other template files). That way you don't have to manually add it everywhere.

**Comment by ACharbonneau** [comment]
Ok...I just looked and we already have one...François beat me to it :) https://github.com/carpentries/.github

**Comment by karenword** [comment]
I'm going to guess that @zkamvar might have thoughts on this? Also yay and welcome awesome new Trainers!

**Comment by brownsarahm** [comment]
This doesn't work 100%, because the LC, DC, and SWC lessons are in separate organizations, but it's only 4 to manually propagate. 

I guess then this becomes is it ok that that there are be lesson-specific styles aspect that we keep notes of in individual repository, (/on the team page for those maintainers) or should everything be standard and in an org level .github?

**Comment by zkamvar** [comment]
> This doesn't work 100%, because the LC, DC, and SWC lessons are in separate organizations, but it's only 4 to manually propagate.
> 
> I guess then this becomes is it ok that that there are be lesson-specific styles aspect that we keep notes of in individual repository, (/on the team page for those maintainers) or should everything be standard and in an org level .github?

Why not both? I think it would be best for an org level `.github` repo (which all orgs have) because that way it will show up by default. If lesson maintainers want to modify the style of a particular lesson, they can have their own CONTRIBUTING.md and link to the default while indicating modifications. Having it public is key so that it's clear for contributors who don't have access to the maintainer teams.

**Comment by brownsarahm** [comment]
I agree that if we *do* have specific styles, they should be recored, but my question was supposed to be *should* we have separate specific styles.

**Comment by karenword** [comment]
For the time being, we decided to store stylistic data specifically useful to this repository in an issue for this purpose: https://github.com/carpentries/instructor-training/issues/1173

If we can customize our own CONTRIBUTING.md (sounds like we can?) we may want to link to this new resource issue, particularly if it accumulates more detail.
