### ISSUE TITLE
Preparation for Community Discussion as part of Checkout 

### ISSUE THREAD

**Issue by klbarnes20** [carpentries/instructor-training#1193]
One person commented on a Community Discussion Feedback Form: "The preparation for the discussion that we received in advance (preparing points to talk about a lesson) was not the same as what we did in the call. " 

And it is true that what trainees are asked to prepare on this [Checkout Procedure Page](https://carpentries.github.io/instructor-training/checkout/) is not always the format community discussions take. Although any extra prep with the lessons is good for a new instructor, I can imagine that sometimes people could be frustrated if they prepare questions and comments and then don't get a chance to use them. 
  
Do others think that what we ask trainees to do for the community discussion matches what happens in a community discussion?

**Comment by ChristinaLK** [comment]
This is a good question @klbarnes20 . I think *most* community discussions follow the format of debrief/ask questions, but topical calls do not. This might be a question for the instructor development sub-committee that technically "owns" these calls...

**Comment by brownsarahm** [comment]
In the [checkout episode](https://carpentries.github.io/instructor-training/20-checkout/index.html), we don't provide much instruction on how to prepare, it links out to the community discussion page in the handbook. 

The discussion page of the checkout procedure page is basically outdated, the name was changed, but no notes about the format changes have been made. see [blame](https://github.com/carpentries/instructor-training/blame/gh-pages/_extras/checkout.md) 

We should probably update that page to either:
- note the fact that some of them are themed and would have a different format & participation would vary
- link to the handbook page instead of providing details at all to reduce future maintenance.

Maybe we should even do a little bit of each, providing a link where the IDC maintains the main info and have a little extra context for new trainees on the checkout procedure page.
