### ISSUE TITLE
Duration of Instructor Training

### ISSUE THREAD

**Issue by Niel27** [carpentries/instructor-training#1284]
<details>

<summary><strong>Instructions</strong>
The training is very good but my suggestion is the duration of the training should take into account the level of of expertise cause some people may have a background example in R or python but do not use them everyday. 
</summary>

Thanks for contributing! :heart:

If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.

You may delete these instructions from your comment.

\- The Carpentries
</details>

**Comment by libe2** [comment]
I suggest that the trainers should consider training for two weeks to allow trainees to digest the materials because the curicullum was too compact

**Comment by brownsarahm** [comment]
Thanks @Niel27 this lesson does not rely on trainees expertise in R or Python, it's for instructors. Local communities can change the format of workshops they teach to accommodate learners or form additional study groups after. 

@libe2 Some locales do various lengths of training for local events through memberships. We are considering collating that information as the trainer leadership panel as well, so I'm linking our [(draft) proposal](https://github.com/carpentries/trainers/issues/127) to this issue, but I'm going to close this issue because it' will be a procedural/organizational change that occurs outside of the contents of the lesson.
