### ISSUE TITLE
Confusion on how and when an instructor profile is created

### ISSUE THREAD

**Issue by wmotion** [carpentries/instructor-training#1291]
The information in https://carpentries.github.io/instructor-training/checkout/index.html#4-tracking-your-progress states that a profile in the Carpentries database AMY is created **after** the Instructor Training workshop **by someone else**.

On the contrary, the section "There are two ways to access Instructor Training" at https://carpentries.org/become-instructor/ mentions that a profile is created **by the candidates** themselves **before** the workshop, when they sign up. "When you register, you will also be asked to create a profile in our database".

At this point it is not clear which procedure applies, whether the two statements refer to the same profile in the first place, and how one should interpret it when the access to the Carpentries database is denied (that is, is the failure expected or unexpected?).

**Comment by karenword** [comment]
Thank you @wmotion ! This is a consequence of a recent change in the language we have been using to describe what was previously known as our "application form". Since that form is now called a "profile creation form" for members, we need to update this section to reflect that. 

The two statements do refer to the same profile, and this is created by 1) the trainee filling out the form and 2) having that form matched in our database to a training, at which point a "profile" is created. I will update the language accordingly!
