### ISSUE TITLE
Direct trainers to have live captions on by default

### ISSUE THREAD

**Issue by brownsarahm** [carpentries/instructor-training#1399]
## 6. Useful adaptations – things which went well

Live captioning in Zoom was incredibly useful. I only realised that I could request this on the afternoon of the second day. This allows participation with the sound turned off (addressing auditory sensitivity), and to use the transcript to catch up if a momentary loss of concentration means that content has been missed.

Perhaps trainers can be encouraged to turn this on by default! I also noticed however that when Zoom breakout rooms are used the subtitles turn themselves off and have to be manually reactivated when returning to the main room. The use of breakout rooms did really gave a sense of meeting people, however, which was great.

_Originally posted by @sjmf in https://github.com/carpentries/instructor-training/issues/1395#issuecomment-1163278874_

**Comment by CassandriaTayFernandez** [comment]
I agree with this. Partway through a community discussion, the person directing the discussion remembered to turn them on and helped me focus immediately. It would have really helped during my instructor training, and the captions would have also helped in the breakout rooms too!

For the breakout rooms to have Close captions, [Zoom recommends using 3rd party software](https://support.zoom.us/hc/en-us/articles/207279736#h_a5d8ae2e-1fc0-425a-9e87-0c612e062fde). Would it be possible to implement that in our courses? It may be a big ask because it involves 3rd party software, and I can't even pretend to know how it would work, but it would be really useful.

**Comment by karenword** [comment]
Thanks @CassandriaTayFernandez ! @brynnelliott @maneesha any prospects for captioning in breakouts?

**Comment by maneesha** [comment]
Live transcription is currently not supported in breakout rooms.  
A participant can be assigned to type in a breakout room, but that does require having a person in this dedicated role. 
Third party software tools exist but we would need to be aware costs and/or privacy concerns and/or the need for additional software maintenance this would require.  I'm adding this to the Infrastructure Team road map. 

@brynnelliott if you are familiar with any tools in particular, your feedback is welcome! 

Read more: https://support.zoom.us/hc/en-us/articles/207279736-Managing-manual-captioning

**Comment by brynnelliott** [comment]
The other option is to have a breakout room in the main room - this is not the best option, depending on how the breakout rooms are being used. 

We are working on building up our accessibility fund, so we can have a 3rd party do the captions at some of the workshops, though, this would need to be requested before the workshop so there is time to set it up. 

@CassandriaTayFernandez @brownsarahm you can always request the host term them on - zoom has a built in button to ask they be turned on.
