### ISSUE TITLE
Broken links in Instructor Notes

### ISSUE THREAD

**Issue by marklcrowe** [carpentries/instructor-training#1501]
The Building Skills with Practice episode (https://preview.carpentries.org/instructor-training/instructor/02-practice-learning.html) includes an instructor note with examples of mental models. The links in this note are broken, and give a 403 Forbidden error.

**Comment by brownsarahm** [comment]
I filed a sandpaper issue because this is an issue in how links are converted in the build process and though we could manually fix them, a long term more maintainable solution is for this to be fixes in the build tools. 

A manual workaround is to delete the solo **instructor** from the path so that:
```
https://preview.carpentries.org/instructor-training/instructor/fig/array-math.png
```

becomes 
```
https://preview.carpentries.org/instructor-training/fig/array-math.png
```

We could manually update all of the paths to be the full path of the rendered images for now, but that fix would break again when we move from `preview.` back to this being the main version.

**Comment by zkamvar** [comment]
Another solution is to render them as actual images and add extra width attributes to make them smaller:

```markdown
![Array Math](fig/array-math.png){width="10%"}
```

**Comment by brownsarahm** [comment]
I like the idea of the rendering them small, but then would still want to allow clicking on them to see the full version (though some people may know that you can right click and open images in new tabs, not all will).

**Comment by zkamvar** [comment]
I've pushed a fix in sandpaper 0.11.9 and it should be available widely in about an hour. Once it is updated on https://carpentries.r-universe.dev/sandpaper, you can go to https://github.com/carpentries/instructor-training/actions/workflows/sandpaper-main.yaml to rebuild the lesson to fix the links.

**Comment by zkamvar** [comment]
And I apologise for this taking longer than expected. The last few weeks have thrown a few challenges my way.

**Comment by karenword** [comment]
This is now fixed. Thanks @marklcrowe !
