### ISSUE TITLE
More clarity on notes guidance for demo rubric

### ISSUE THREAD

**Issue by aj-stein-nist** [carpentries/instructor-training#1654]
### How could the content be improved?

I recently completed instructor training and @froggleston recommended that if I open an issue to consider something that would be more clear, at least to me, on good practice for the use of notes while performing a lesson, particularly these two lines.

|  Positive Delivery                 | Delivery Opportunities for Growth                      |
|-------------------------------|-----------------------------------------------------|
| Uses notes on paper/tablet | Displays lesson materials/notes on their screen |

Is this to suggest I should not have relevant notes or lesson materials generally? I know the instructor training focuses on in-person and the online training in order of preference (for centrally managed events), but I was curious why for the demo, and maybe online trainings, I should not keep the lesson material of one half of the screen and the code window on the other. In demo practice in training I received positive feedback for that, but this rubric implies that, at least for an online demo to get certified, that it is discouraged.

1. I am interpreting this correctly?
2. Are maintainers open to adjusting the wording to signal this implication if I misinterpreted 1 and the answer is no?

### Which part of the content does your suggestion apply to?

https://carpentries.github.io/instructor-training/demos_rubric.html

**Comment by brownsarahm** [comment]
Your interpretation is correct, we discourage showing the lesson material or notes on the screen because it increases the cognitive load on learners and often means your font size of what you display cannot be large.  

Displaying the material is especially risky if you might skip sections for time, which is *strongly* preferred to going fast. When learners know that you are skipping , some will be confused by that and some may feel that you are skipping because they are not good enough. 

Sharing *only* what you are live demo-ing helps learners focus on your demo and avoid these concerns.

**Comment by aj-stein-nist** [comment]
OK that clarifies, thank you. I won't do it during demo or more generally.
