### ISSUE TITLE
Suggest diagram for 

### ISSUE THREAD

**Issue by adwinters** [carpentries/instructor-training#500]
I suggest incorporating the following diagram under "How Learning Works: Expertise and Instruction":
https://commons.wikimedia.org/wiki/File:TPACK-new.png

This lesson is currently being prepared for publication and is under development at https://github.com/ErinBecker/instructor-training-reorg/. Please submit any issues or PRs to that repo (not here).

**Comment by brendanburkart** [comment]
I like Venn Diagrams, but I don't like this one - it looks overly complicated with the arrows describing what the diagram itself describes.  

Can it be edited to remove those arrows?

**Comment by ErinBecker** [comment]
@adwinters - Thank you for your suggestion. In a previous version of the instructor-training materials, we did have a lesson dedicated to explaining many of the terms that are included in the image you linked. Because we were not using these terms later in the lesson and they were not necessary to understand the materials, we removed this "terms" episode. I do like the TK/PK/CK model for thinking about the development of instructional expertise, but we found that for our purposes this is too much detail to go into during the two day instructor training workshop.
