### ISSUE TITLE
Update code of conduct contact email addresses

### ISSUE THREAD

**Issue by nspies** [carpentries/instructor-training#567]
The instructor training ["teaching practices"](instructor-training/_episodes/22-practices.md) section lists "admin@software-carpentry.org or admin@datacarpentry.org" as contact addresses to report code of conduct violations.

I believe the instructor materials should be updated with the new @carpentries.org email addresses in the [code of conduct itself](https://software-carpentry.org/conduct/), which says that code of conduct violations should be directed to "the joint Data/Software Carpentry (“the Carpentries”) Policy subcommittee by emailing policy@carpentries.org or C. MacDonnell at confidential@carpentries.org".

**Comment by ErinBecker** [comment]
Hi @nspies - thanks for your attention to detail. There are a couple of different reporting types involved in CoC violations. For online incidents people should contact the Policy subcommittee, or if for some reason they'd prefer not to contact them, the confidential@carpentries.org email is an alternate. For cases where the incident occurred at an in-person event, the immediate contact should be the workshop host and/or coordinator. Because the instructor training materials are targeted towards instructors who will be leading in-person events, the workshop coordinator (and/or host) is the appropriate person to contact. The relevant part of the CoC is: 

>> If you believe someone is violating the Code of Conduct we ask that you report it to the joint Data/Software Carpentry (“the Carpentries”) Policy subcommittee by emailing policy@carpentries.org or C. MacDonnell at confidential@carpentries.org, and if the violation occurs during a workshop or other in-person event, by contacting the host and/or coordinator.

I agree that this wording may be somewhat confusing, but it's not a case of forgetting to update the email addresses! If you have a suggestion for making the text of the instructor training materials more clear, please let me know. I'd be happy to implement.

**Comment by nspies** [comment]
Hi @ErinBecker - I think there may have been some confusion about which section in the instructor training I was referring to so I've made a pull request that hopefully clarifies (sorry, this was me trying to do a quick issue report during the relevant part of our training!).

The section in question directs the workshop coordinators to contact those email addresses as follow-up to the workshop and so I do think the instructor materials should include the new email addresses.

**Comment by ChristinaLK** [comment]
This has been resolved by #572, correct?

**Comment by nspies** [comment]
Yes!
