### ISSUE TITLE
Add more info on mental models

### ISSUE THREAD

**Issue by elliewix** [carpentries/instructor-training#584]
The discussion about what a mental model is pretty brief, and we're finding that many of the learners wanted more info and background on it. (sorry for the short issue; in the middle of a workshop, we're going through the feedback.) We had 4 negative feedbacks about this and have had it in previous runs.

**Comment by fmichonneau** [comment]
+1 I have gotten this feedback at previous workshops as well

**Comment by weaverbel** [comment]
I have also had quite a few people say they need more about this - we came back after the break and went over it again in one workshop after seeing in the feedback that people were still confused.  We had more than three people raise this as an issue.

**Comment by ChristinaLK** [comment]
See also #566

**Comment by kariljordan** [comment]
I tweeted this issue. Hopefully someone has a good idea, because I struggle with this as well.

**Comment by ha0ye** [comment]
I'm less of a fan of the term "mental model" and prefer the term "mental map", which is used a bit later in the lesson. To me it is more evocative of the analogy that learners need a way to organize and retrieve information.

I think some helpful examples will clarify why mental maps are important. For example, I imagine teaching workshop attendees about the command line for the first time is similar to users first learning about the mouse with the first macintosh:
https://youtu.be/1pwammW5syw?t=2m25s

The notion that you can lift the mouse to reposition it if you need more space may seem obvious to us (because we are so experienced that it doesn't even register as a conscious action), but certainly not to the first users of a GUI. Similarly, the idea that each command-line session has a working directory may seem obvious to us, but not so for a new user. (And you could certainly do all the shell commands using absolute paths instead of relative paths, so it's not strictly necessary...)

**Comment by ha0ye** [comment]
I had some more thoughts on an example after Instructor Training (👋 at @kariljordan @fmichonneau):

Consider trying to learn to cook.
If you are starting out without a mental model, then performing the act of cooking may be limited to following the instructions of each recipe verbatim.

Over time, just from the experience of implementing different recipes, and maybe even some failures to execute them properly, you might start to recognize some patterns. For example, the ratios of ingredients in baking, what order to prep ingredients, apply heat, season, etc.

At some later stage, with enough experience, you might even recognize where substitutions can be made, because of which ingredients are often paired or swapped in recipe variants. This can even lead to the development of completely novel recipes by knowing what works and what doesn't at each step of the process.

However, that process of acquiring experience and relying on pattern recognition can be slow. Workshop attendees often won't be engaging in the skills they learn at the workshop every day. So helping them develop an explicit mental model will help.

Some cooking classes do this by including instruction on the various steps of a recipe (in contrast to simply going through a recipe each week). For example, discussion of possible ingredients (similarities, differences, why they are included), technique (do you chop into small or large pieces, ensuring similar sizes for even cooking), etc.

**Comment by ChristinaLK** [comment]
This is a great example @ha0ye!  I think we discussed having a "library" of mental model examples and that would fit in really well.

**Comment by karenword** [comment]
OK so because I can't help blending my discussions of mental models with concept maps, and because I love @ha0ye 's idea about a cooking example, I created a list of concepts that might be associated with cooking rice, along with a few prompt questions to think about how a novice might approach this collection when tasked with making a map. This is a sort of a seed and (as I'm sure you will be able to tell) I am NOT an expert chef, so I am sure this could be improved upon if anyone things its useful! 
![conceptmap_cooking](https://user-images.githubusercontent.com/22605448/38750209-0fc40266-3f09-11e8-8aa8-574d4294f7e6.png)

Since this is a concept map (albeit not a computing example) it is also related to https://github.com/carpentries/instructor-training/issues/505

**Comment by karinlag** [comment]
Just a  note from the sidelines here, I just realized that I've always thought of concept maps as a way of illustrating/drawing a mental model... :grin:

**Comment by kristenobacter** [comment]
There was a lesson in my STEM teaching course (An Introduction to Evidence-Based Undergraduate STEM Teaching," STEMTeachingCourse.org) which I think applies here. 

Mental models are important, because they are models that students carry into a new course which can influence their perception of new information. Prior knowledge can be thought of as the ornaments of a tree whose structure is the mental model. If we want to hang new ornaments (new information) it helps to know what's already there. Activating prior knowledge helps to address misconceptions. Here are a few methods for activating prior knowledge:

- ask students to write down what they know about a topic just after introducing it
- alternate between abstract and applied problems
- pause in the lesson to do think-pair-share (don't forget to allocate time to think!)
- administer pre-assessment quizzes (optional or for credit)

Understanding different types of misconceptions can help dispel them. Here we discuss four categories of misconceptions, listed from easiest to address to most difficult to address.

(1) Proposition-level misconceptions. These are "fun facts" that are wrong; knowing whether they are true or false doesn't really affect your life or your vision of yourself. An example is the idea that humans only use 10% of their brains. This is not true. 

(2) Flawed mental models. These are cases where the student has the right metaphor, but the wrong application. An example is how the heart works. Students might know that the heart pumps blood, but not realize that there have to be two separate chambers, one to pump from the lungs to the body (the oxygenated blood), and the other to pump from the body to the lungs (the oxygen-deplete blood). 

(3) Ontological miscategorizations. Ontology is the examination of what is meant by "being," and this kind of misconception is a fundamental misunderstanding about how the world works. It is having the wrong metaphor or lack of a metaphor completely. An example is a circuit with a power source, three bulbs and a switch which closes circuit before the third bulb; not knowing how throwing the switch affects the intensity of the third bulb indicates that you don't know enough about how electricity works to address the question. 

(4) Embedded beliefs. These are misconceptions that are tied to identity, family, culture or community. An example is evolution, where a student accepting this theory of how life became so diverse would have to leave large parts of their social network behind and perhaps fundamentally change what kind of person they imagine themselves to be. It is considered that this kind of misconception is practically impossible to correct. 

I hope this helps address how mental models are formed and improved upon! I'm happy to provide more citations if that would help.

**Comment by ChristinaLK** [comment]
Thanks @kristenobacter ! We have some of the misconceptions that you've described already in the instructor training material, but not the distinction between 2 and 3. We also don't explicitly talk about activating prior knowledge (I think), so that might be a good addition to the material.
