### ISSUE TITLE
Updating coverage of mindset

### ISSUE THREAD

**Issue by gvwilson** [carpentries/instructor-training#618]
(relocated from #616)

[This article](https://educhatter.wordpress.com/2017/03/26/growth-mindset-is-the-theory-flawed-or-has-gm-been-debased-in-the-classroom/) is a good summary of challenges to mindset theory and ways in which it is being mis-used - if were going to cover mindset in workshops, should we be pointing at these reservations and qualifications as well?

**Comment by ChristinaLK** [comment]
I'm interested to know what @kariljordan @ErinBecker @maneesha and @karenword think about this.

**Comment by kariljordan** [comment]
I think we should revisit the point of discussing growth versus fixed mindset. I believe our goal is to teach our community that we promote continuous learning and that you don’t have to be “born smart” to learn programming. I do not know how much value we’d add by discussing the challenges of this theory. Those are my initial thoughts after taking a glance at the article. What does everyone else think?

**Comment by ErinBecker** [comment]
I agree with @kariljordan. For any of the topics that we cover in our training, we could go into a lot more detail, including talking about alternative theories and controversies, but I consider that outside of the scope of our training. The point of introducing growth mindset is to help instructors shift their view about learning so that they are patient and compassionate with new learners who are facing challenges and continue to offer them support rather than giving up on them. I don't think we would add anything for the instructors by talking with them about how growth mindset has been misapplied (or not) in various settings.

**Comment by gvwilson** [comment]
More on growth vs. fixed mindset: https://twitter.com/StuartJRitchie/status/970755035964624897 (summary) and http://journals.sagepub.com/doi/abs/10.1177/0956797617739704 (source).

**Comment by ChristinaLK** [comment]
I'm agree with @kariljordan and @ErinBecker -- maybe the change to make to the material (if any) is to use the fixed/growth mindset theory as a way to frame the other topics in that section -- that learning is a process and, with practice, anyone can improve on their current skills.

**Comment by raynamharris** [comment]
bump. was this addressed at all in the recent revamp of lessons? I noticed this open issue when I search for "mindset" before creating #845.

**Comment by ChristinaLK** [comment]
Not really -- @karenword and I discussed this at some point but didn't make any changes.  

I found that I leaned really heavily on the mindset language when I taught this last time because it really captures a lot of the *other* things we talk about: teaching is a skill that can be learned (which is similar language to "growth" mindset), we care about life-long learning, etc.  It was like the hub with useful spokes (lifelong learning, grit, supported practice, motivation) coming out of it. 

Maybe the main idea is (as I said above): "learning is a process and, with practice, anyone can improve on their current skills" and we highlight how different researchers have investigated that theory (mindset, grit, etc.) but we don't tie it so exclusively to "mindset."
