### ISSUE TITLE
A better illustration of concept maps

### ISSUE THREAD

**Issue by gvwilson** [carpentries/instructor-training#622]
![screen shot 2018-02-13 at 9 38 58 am](https://user-images.githubusercontent.com/911566/36155253-e12c204a-10a1-11e8-9532-eb7a58e049c6.png)

Taken from:

```
@article{Keppens2008,
  doi = {10.1080/08993400701864880},
  year = {2008},
  month = {mar},
  publisher = {Informa},
  volume = {18},
  number = {1},
  pages = {31--42},
  author = {Jeroen Keppens and David Hay},
  title = {Concept map assessment for teaching computer programming},
  journal = {Computer Science Education}
}
```

**Comment by arokem** [comment]
This is way bigger than 7 +/- 2!

**Comment by ChristinaLK** [comment]
I'm -1 for adding this.  I don't think you need to know much about the content of a sample concept map to learn about/understand what a concept map *is*, but I do think you need some context (so that the blocks + arrows make sense) and this content seems too technical for me.

**Comment by katrinleinweber** [comment]
Very "Technical" in the sense that it relates to app(lication) development, yes. However, since all learners probably use GUI app(lications), it might be a motivating look "behind the scenes" so to speak. Thus, not "too" technical, although using this I would look up a definition of each of the terms in those nodes.

**Comment by amyehodge** [comment]
I agree with @arokem and @ChristinaLK that this is both too many pieces of information and too technical. I have many questions about what the parts refer to (like "event handlers" -- is that a person like I think "layout manager" is, or a piece of code?) before I even can think about this as a concept map.

**Comment by katrinleinweber** [comment]
Except for the "user, yes, these all seem to be pieces of code / components of an app.

The `layout manager` draws the GUI elements like buttons, texts etc. according to the screen/window size. On an iPhoneX even around the notch if necessary ;-)

`event handlers` are templates for `listeners`, which are the app components that wait for some kind of user input/interaction and then do something (`manipulate`/update/create/delete a `data model`/file or a `UI component`).

Such explanations are what I meant with "look up a definition". If the diagram is used, the instructor needs to be able to explain each element roughly. Not easy, but doable. And because what those things _actually do_ should be familiar to all learners, because they all are probably using GUI app(lication)s all the time. So the question IMHO is whether this "look behind the scenes" is worth preparing given it's technical complexity vs. it's potential to be motivating and partially familiar.

I'm trying to find an analogy for this discussion using a class of pupils, their physics teacher and the destination of a field trip. Maybe: "Should the teacher prepare a trip to a cinema museum, so the pupils can learn about technical details of light & sound projection, in order to understand the physical concepts better? Because everybody knows what a cinema is and what it does for the audience."

I hope this makes my argument about the necessary explanations of this diagram clear :-)

**Comment by amyehodge** [comment]
@katrinleinweber My issue then would be with needing to take the time to review the definitions of everything to make sure everyone is on the same page before the

**Comment by mir-cat** [comment]
I think making a content map based on the content of the memory module itself could be a good idea. Because the material was just covered, it should be fresh in everyone's mind, leaving them free to focus on the structure of content maps, not the particular content of the example. 

This could be the unconnected concept map:

![hikl-2](https://user-images.githubusercontent.com/10320217/59546380-6771f300-8efa-11e9-8a17-1ed8f35ac4be.jpg)

And this the connected one.

![hikl-1](https://user-images.githubusercontent.com/10320217/59546546-61c9dc80-8efd-11e9-9de3-cadfc97ffdf2.jpg)


A second example can show how a concept map can be used to divide knowledge into digestible chunks.

Here is a larger concept map on the same material.

![hikl-3](https://user-images.githubusercontent.com/10320217/59546554-8756e600-8efd-11e9-83ff-a5e9cb77ed87.jpg)

While the first concept map was small and digestible, this one is larger and more daunting. However, it can be divided into two lessons. The first describing a general flow of knowledge to short term memory. (Same concept map as above), 

![hikl-1](https://user-images.githubusercontent.com/10320217/59546576-f0d6f480-8efd-11e9-90ec-956fe5fe0ee9.jpg)

and another describing activities that help move knowledge from short to long term memory.

![hikl-4](https://user-images.githubusercontent.com/10320217/59546565-cdac4500-8efd-11e9-8cca-a12cf5e2f7fe.jpg)

The knowledge in the larger graph can be taught by teaching each of the two smaller graphs, capping each with an activity to make the knowledge stick. Which hopefully the learners can appreciate, since they just went through that exact lesson structure and remember this information :P.

**Comment by erjank** [comment]
There's a discussion occurring in the April 7 2022 Instructor Trainer's meeting right now about Concept Maps in instructor training, including how much everyone likes talking about concept maps, but how they might be a part of the curriculum that could be trimmed down. One recommendation that stood out to me was like the above, making a specific example of a concept map that's built up and connected to content. The specific example we discussed was the addition diagnostic  multiple choice question. Other points raised were that (a) We want to illustrate how teachers could use mental models to diagnose how learners think about concepts, and (b) Making concept maps in-class adds a lot of cognitive load, especially around possibly using a new tool, and (c) Everyone likes learning little personal snippets from their classmates from seeing their concept maps.
