### ISSUE TITLE
Improve day 2

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries/instructor-training#641]
We've gotten comments that Day 2 is slower and less interesting for folks and we'd like to punch it up (while also retaining our pedagogical integrity ;)).  

Already done: 
- worksheet matching exercises for different roles in the community by @amyehodge 

Suggestions: 
- do the history / numbers piece of The Carpentries as a "pop quiz" cc @ErinBecker (it would be fun to do a "wits and wagers" type setup for guessing the carpentry numbers --countries, workshops, instructors.  --@christinalk)
- make the introductions section more learner-driven.   @ChristinaLK has done this at Madison, see https://github.com/ChristinaLK/swc-lessons/blob/master/intros/intro-notes.md
- move some of the carpentries material to the morning of Day 1 to orient people (and shift everything back a bit)

**Comment by gvwilson** [comment]
I used to open with an intro to the Carpentries, but got complaints that it was "all admin stuff" up front. Opening with novice-competent-expert and diagnostic power of formative assessments has worked much better, since it gives people something unexpected and useful right off the bat. (Saying this doesn't help improve day 2, of course…)

**Comment by sheraaron** [comment]
I would agree that moving some of the information to day one would be beneficial. It will also give learners an insight into who the Carpentries is, if they have no clue.

**Comment by ChristinaLK** [comment]
@gvwilson, @karenword also liked starting w/ the mental model stuff so I think we're thinking "Carpentries lite" as an opener.  Maybe I'll open a separate issue about that...

**Comment by kariljordan** [comment]
I find it really interesting that people feel day two is less interesting, when that's when most of the active learning takes place, or maybe it's just the way I teach it. 

I must confess, I never use the worksheet.

+1 to moving a bit of "who we are" (Carpentries) to day one because some people really don't know. Some are "voluntold" to attend training and don't really know who we are and what we do.

**Comment by ChristinaLK** [comment]
#778
