### ISSUE TITLE
Post Survey Link

### ISSUE THREAD

**Issue by sheraaron** [carpentries/instructor-training#652]
I have been asked by several instructors where the link is to the Post Survey. Currently, it is in the curriculum under wrapup. Would it make sense to also have it on the workshop website, similar to regular DC/SWC workshops?

**Comment by karenword** [comment]
It is also in the etherpad template for that curriculum piece. I wonder if instructors inquire when they are looking for it after the workshop to remind their learners to take it? In that case we should have it in an email template for that purpose.

**Comment by raynamharris** [comment]
Interesting, this probably could've been closed a while back, but ...

I added links to the LC pre and post workshop surveys in PR https://github.com/carpentries/instructor-training/pull/814 (specifically with commit https://github.com/carpentries/instructor-training/pull/814/commits/e7472fb5a08f10cd037752638813d603ea1de970). The only thing is that my LC links go directly to the survey rather than a preview. Maybe someone has a better link to the preview?
