### ISSUE TITLE
Metacognition, Bloom's, etc.

### ISSUE THREAD

**Issue by PLNReynolds** [carpentries/instructor-training#658]
I think it would be really useful to include some more formal metacognition framing, such as Bloom's Taxonomy, and how it can help you address and assess "meeting learners where they are." Discuss?

**Comment by ChristinaLK** [comment]
We used to have Bloom's in the episode on lesson study (http://carpentries.github.io/instructor-training/14-lesson-study/); I'd be interested in putting something about it back.

**Comment by ha0ye** [comment]
I am personally not a fan of the hierarchy of Bloom's taxonomy, but I think a listing of the different (fuzzy) categories, and related terms and synonyms would help instructor-training-participants develop effective, specific learning objectives.

**Comment by karenword** [comment]
This topic arises from conversations we've been having about Dr. Rochelle Tractenberg's webinar (summarized here: https://software-carpentry.org/blog/2018/03/tractenberg-summary.html) and visit to our assessment network meeting. Specifically, she talks about preparing learners to "grow a level" and also to develop awareness of the ways in which they should expect to continue advance their learning when they leave.

**Comment by ha0ye** [comment]
I agree that there is some sort of spectrum of complexity for learning objectives, and that the ordering of Bloom's Taxonomy corresponds roughly with how I would order them.

My complaint is primarily with the presentation of the different levels as being like linear goalposts. For example, I don't think it's necessary to "master" B1 through B5 in order to accomplish B6.

I also worry that the ranking of the objectives creates negativity for learners who don't master all of the learning objectives. I like the idea of "meeting learners where they are", and I think it should be accompanied with "get learners where they want/need to go". I don't want anyone to feel like they're a failure if they don't get to the "Evaluate/Compare/Judge" stage.

**Comment by PLNReynolds** [comment]
Those are interesting points and should be addressed in the framing and conveyance of how to talk about metacognition, especially if instructors were to bring it up to their learners. Since we are talking about instructor training with self-selecting individuals interested in pedagogy, including core educational theory like metacognition would give them ideally better depth in understanding ways to meet learners where they are, to understand why lessons are structured the way they are (and how to evaluate where and when they might want to make changes for a given audience), and to be conversant with other educators and trainers. This is biased as for the instructor training I attended most if not all individuals were graduate students or postdocs looking for this level of background in the instructor training (but correct me, Karen if I’m wrong there).

Looking forward to thinking more on this at the bug BBQ tomorrow, and happy to ping my faculty contacts at the School of Education here (one who is working on a NSF NRT grant on modes of computational skills instruction in graduate education) if other viewpoints would be helpful.

~Pamela

**Comment by karenword** [comment]
Bloom's has been added back in to the most recent updates, currently here: https://data-lessons.github.io/instructor-training/15-lesson-study/index.html. I'm not sure that all of these concerns have been adequately addressed, so feel free to launch a new discussion based on those changes!
