### ISSUE TITLE
Inconsistency in recommendation to email "checkout@carpentries.org"

### ISSUE THREAD

**Issue by symulation** [carpentries/instructor-training#684]
Episode #23 (https://carpentries.github.io/instructor-training/23-checkout/) suggests that two sources could be referred to for how to checkout:

1.  The details (https://carpentries.github.io/instructor-training/checkout/)
2. The "helpful checklist" (https://carpentries.github.io/instructor-training/checkout/)

There is an inconsistency between these two sources: The helpful checklist clearly makes emailing checkout@carpentries.org something that needs to happen after a lesson contribution has been made while the details page is silent about this.

The solution seems to be that either the instruction needs to be added to the details page OR it needs to be removed from the helpful checklist page, depending on what the actual process is.

**Comment by ErinBecker** [comment]
Thanks @symulation for your careful reading of the materials. We do need to add the instruction to email checkout@carpentries.org with a link to the lesson contribution to the details page (https://carpentries.github.io/instructor-training/checkout/). @karenword - can you add this link please?

**Comment by karenword** [comment]
Actually the details page does include this information -- it's just lower down on the page with the detailed instructions for the lesson contribution ("Part 1").  It states "1. If you submit your contribution through GitHub, you need to send us a link to the pull request or issue so that we can track your progress through checkout." I have submitted a PR that features this information more prominently at the top of the page.
