### ISSUE TITLE
mention #welcome slack channel

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/instructor-training#721]
Towards the end of the workshop, it might be good to add a mention of the Slack #welcome channel. Learners could even have a chance to practice their "how to introduce yourself" skills by spending a couple of minutes writing a two-sentence summary about themselves and responding to someone else's introduction.

**Comment by ChristinaLK** [comment]
Could be added to http://carpentries.github.io/instructor-training/20-carpentries/ under Carpentries Community.

**Comment by kariljordan** [comment]
I'm a fan of asking trainees to introduce themselves on the welcome channel. It has been helpful to keep traffic off of #general. I do understand the concerns about us using Slack in general though, and didn't realize this was the case. I've brought this to the attention of staff FYI @remram44. Thank you for your insight!

**Comment by annajiat** [comment]
Thanks to @remram44 for the highlights. Some organizations have indeed been checking out alternatives like Discord. Since Carpentries seem to use a paid version of Slack, the messages persist. Until we choose to move to an alternative as a part of long-time strategy, we may choose to make the experience smooth for the newcomers by following the suggestions of @fmichonneau and @ChristinaLK 

In general, introductions have been discussed under [Launches and Landings](https://carpentries.github.io/instructor-training/23-introductions.html). With the updated training material, I came across three locations for implementing this suggestion. We may choose to do all of the following three. 

1) Under [Keeping un Touch
](https://carpentries.github.io/instructor-training/15-carpentries.html#keeping-in-touch)

So, it may look like: (changes in bold)
Want to interact (or listen with options to engage)?
    Join our Slack organisation **(start with Slack #welcome channel)**
    Join our Email lists (start with “Discuss”!)

2) During the actual [introduction practice](https://carpentries.github.io/instructor-training/23-introductions.html#practice-your-introduction)

3) At [Connecting with The Carpentries](https://carpentries.org/connect/) on the website.

Looking forward to comments and suggestions from the community...

**Comment by brownsarahm** [comment]
this issue is not related to launchings and landings only to "keeping in touch"

the carpentries website is out of scope for issues on this repo. 

However, the modified keeping in touch exercise, I think, closes this (very old) issue.
