### ISSUE TITLE
Changes to section on setting up a workshop website.

### ISSUE THREAD

**Issue by ha0ye** [carpentries/instructor-training#729]
This section feels like it is both too much for attendees who don’t have the background in git and GitHub, and also not enough information on how to run a whole workshop.

Consider replacing it with an overview on different pathways to contribute to the Carpentries.
(cc @raynamharris, @tracykteal)

**Comment by arokem** [comment]
This was also discussed in https://github.com/carpentries/instructor-training/issues/681

**Comment by raynamharris** [comment]
Thanks, @arokem, I do remember a discussion where there was a lack of consensus about keeping it. Could we move this exercise somewhere else and link to it? Perhaps the [lesson example](http://carpentries.github.io/lesson-example/) repo?

**Comment by arokem** [comment]
Funny that -- I remembered a lack of consensus about removing it ;-) 

Why would we move it to the lesson example?

**Comment by raynamharris** [comment]
:) half full/ half empty, depends on who you look at it. 

I'm not convinced that lesson example is the right place, but I was just trying to think of somewhere where we teach people how to use GitHub for using Carpentry materials. The Lesson Example is all i can think of. The workshop repo readme explains who to make your own workshop website, but I don't know where one would add an exercise for creating your own workshop there.

**Comment by karenword** [comment]
The question of where to cut is a big one, and this is something that @ChristinaLK and I have been talking a lot about, since we actually need to cut some content as-is, even if we don't add anything new. While it is necessary to remove content in order to make room for new ideas, these conversations get complicated when we combine two proposals -- what to cut and what to add -- in the same issue. Since we already have an issue for discussing the proposed removal of the workshop website content, I suggest we use this issue (or create a new one) to discuss the excellent suggestion that we add content describing different pathways towards involvement with the Carpentries.

**Comment by arokem** [comment]
Added #730 for that discussion.

**Comment by ChristinaLK** [comment]
Closing for now.  I'm adding a note in the instructor's guide about it.
