### ISSUE TITLE
Relevance of struggles/disabilities in learner profiles

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/instructor-training#740]
(moving here from https://github.com/swcarpentry/website/issues/1044)

[Learner profiles on the Software Carpentry website](https://software-carpentry.org/audience/) have a set of struggles/disabilities (added through https://github.com/swcarpentry/website/pull/576):

- celiac disease
- nearsightedness
- family with small children and undiagnosed depression
- attention deficit disorder

These seem to have been accepted without discussion (at least on GitHub, I may have missed a discussion elsewhere). 

I understand the thought, our learners are diverse and may be struggling with issues we don't see. The author of the PR writes "I have had students with all of these personal challenges in class." However, these struggles/disabilities seem a bit out of place. I am not sure whether they are relevant in the context of our workshops. 

Open for discussion, and to kick this off I provocatively suggest too remove them.

**Comment by ChristinaLK** [comment]
@lexnederbragt these were added after an instructor training I did in Wisconsin. :)

I like having at least one or two examples (near-sightedness + depression are the ones I'd pick) of disability/mental health.  People's abilities/disabilities are definitely relevant if their abilities/disabilities will otherwise impede their learning and we want to reach them.  Including this information highlights learner's needs beyond "missing technical skills" and so can help us think about designing workshops that aren't just about communicating technical skills, but building community.  I could be convinced to remove one or two examples, but I think it's appropriate and important to have these aspects of life as part of the learner profiles.  

No matter what, it might also be a good idea to put some of these examples into the accessibility module!

**Comment by amyehodge** [comment]
I would vote for figuring out a way to better integrate these into the profiles. The last one says, "In high school, Mehrdad was diagnosed with Attention Deficit Disorder, which he learned to manage." Perhaps in the final paragraph that starts "Software Carpentry will teach Mehrdad how to....." we could say something like (assuming there is support for this and keeping in mind that I know nothing about ADD), "The hands-on style of Carpentries workshops and the short sections of talking interspersed with activities make it easier for Mehrdad to learn in this environment, despite his ADD." That way it feels more integrated with the rest of the profile and a bit of an "explanation" is provided for why it's there. But I admit I chose an easier one, as I don't know what to say for the person celiac, for example. But I do feel that more context for the comments would be helpful. At least a comment on why this increases the challenge.

**Comment by lexnederbragt** [comment]
@amyehodge That is a really good idea! Who could we ask to put in a PR for this?

**Comment by maneesha** [comment]
@amyehodge  said:
>  "The hands-on style of Carpentries workshops and the short sections of talking interspersed with activities make it easier for Mehrdad to learn in this environment, despite his ADD." 

Do we actually know that our teaching style is better for people with ADD?  I wouldn't want to say something like that unless we can demonstrate why this is so.

When I teach that section, I think of it more as @lexnederbragt  noted, that "our learners are diverse and may be struggling with issues we don't see."   This means we as Trainers/Instructors have no idea what's going on in people's lives outside of this workshop.  We need to recognize that maybe someone needs to hear something more than once due to ADD, or maybe they have to sit on the left side of the room because of a hearing impairment, or whatever the case might be.  Maybe someone's just had a really crappy week, making it difficult to focus.

We should be prepared and welcoming to these accommodations without judgement, and even without explanation.  If they want to sit on one side of the room, they shouldn't have to tell us it's because they are deaf in one ear (unless they want to).  They should sit wherever makes them comfortable, and we should go with it.

Asking to sit on the left side of the room isn't an accommodation that requires advance preparation.  However, others like needing wheelchair access, or dietary restrictions, do need advance preparation.  That's where I talk about the planning phase of the workshop, where it is important to be sure learners are asked when registering for the workshop if they need anything that will make it easier for them to fully participate in this experience.

**Comment by amyehodge** [comment]
@maneesha Just to clarify that I made the qualification I did in my comment because I don't know anything about ADD. It was just an example of something that sounds more integrated. I am not at all attesting to the actual validity of that statement and indicated that whatever was said would have to be verified/qualified/whatever if we wanted to take that approach.

**Comment by ChristinaLK** [comment]
@maneesha what do you think about having something like ADD in the learner profiles vs having more text (like you've described) when we talk about setting up workshops?

**Comment by maneesha** [comment]
@ChristinaLK   I understand the motivation behind the profiles, to understand that everyone is coming in as complex humans, all with different drives, skills, experiences, advantages, and challenges. Recognizing this is an important value of our training program.  

At the same time, I do often feel like the profiles come across as contrived caricatures.  I'm not volunteering myself to do this because it would be a lot of work :-) but  I wonder if we could gather authentic (anonymous) testimonials instead.  

I don't know if I'd put more into the section about setting up workshops because the instructors aren't always responsible for all that set up - it is often the host site that does this.

And @amyehodge  thanks for your comment.  Yes, I should have acknowledged your disclaimer, and meant that if we make any kind of statement like that, we should be sure it is based in fact.  I apologize that it sounded personal.

**Comment by dvanic** [comment]
@maneesha I wonder if an easier/somewhat representative approach would be to ask existing instructors to write up (anonymous) profiles of themselves when they first came to the carpentries, and/or profiles for some of their most "challenging" students (challenging in this case meaning students who challenged them the most as teachers/workshop leaders)?

/albeit I acknowledge there is a bias since not all workshop attendees will consider going on to be instructors, meaning our sampling would inherently not be representative - but perhaps more representative/less "fake" then what we have now, or one person rewriting it in theory/?

If we have too many responses - then perhaps having a reddit style thread where we could upvote profiles as "critical" for inclusion on this page, and then including the top 20 on this page, and the others on a "more profiles" one?
