### ISSUE TITLE
Instructions about instructor page

### ISSUE THREAD

**Issue by weaverbel** [carpentries/instructor-training#753]
Do we need to update anything anywhere about how people can get to appear on the new instructors page once they are certified? I see people are still emailing in pictures and short bios when these are no longer needed.

**Comment by weaverbel** [comment]
Will make a task for EB to update that then.

**Comment by ErinBecker** [comment]
Thanks for following up on this @weaverbel. The email that I've been sending out has been up-to-date since we made the change about instructor bios and mailing lists, but many people wait quite a while to follow the instructions in the email so we're still getting some people from back in June who are sending in bios. I've updated the text of the email in the handbook and will continue to use the up-to-date version in my script. 

Noting here also that @fmichonneau proposed a strategy for keeping local scripts up to date with the email template in the handbook (https://github.com/carpentries/handbook/pull/232). I will look at that and follow up with him and @maneesha about that strategy.
