### ISSUE TITLE
"live coding" vs "code-along"

### ISSUE THREAD

**Issue by karenword** [carpentries/instructor-training#776]
I think this Topicbox conversation needs an issue!

https://carpentries.topicbox.com/groups/discuss/T69368b0ceffc20b9/whats-in-a-name-live-coding-or

**Comment by ChristinaLK** [comment]
So the question is: do we need to change all our references to live-coding to code-along?

**Comment by raynamharris** [comment]
It might take an hour, but I say yes. If you go with the more formal "participatory live coding" it will be a quicker fix. But you might want to add code along in there too. 

I didn't contribute to the dialog, but I agree that this phrase better captures the workshops style. I've been to countless workshops where the presenters used live coding but people couldn't follow along (because of access restrictions or something) or weren't encouraged to code-along.

**Comment by raynamharris** [comment]
cc @lexnederbragt

**Comment by lexnederbragt** [comment]
Thanks for the issue, @karenword! 

I would prefer "participatory live coding" as the term for what we do, with "code-along" as nickname and to 'sell' it to learners. Making the necessary changes will take some time, yes. I'd be willing to do it but can't commit until late November/early December...

**Comment by ChristinaLK** [comment]
Okay, this is ready for a PR whenever someone has time.  :)

**Comment by raynamharris** [comment]
I'll do it!

**Comment by ChristinaLK** [comment]
Rayna, can you submit the PR against data-lessons?

**Comment by raynamharris** [comment]
Thanks for clarifying. I was about to ask!

**Comment by ChristinaLK** [comment]
@raynamharris I just granted access to the repo.

**Comment by raynamharris** [comment]
@lexnederbragt I just submitted PR https://github.com/data-lessons/instructor-training/pull/26 let me know what you think!

**Comment by lexnederbragt** [comment]
Thanks to @raynamharris now merged into https://github.com/data-lessons/instructor-training!
