### ISSUE TITLE
Data Carpentry Instructor Training

### ISSUE THREAD

**Issue by Valbat** [carpentries/instructor-training#785]
I think it would be good to add as a requirement or recommendation that the instructor give a quick summary about Data Carpentry's organization and mission and that the trainers are volunteers.

**Comment by Valbat** [comment]
I would put the mission of the Data Carpentry organization up front and center. I would state the mission at the top of the page. In addition, one of the challenges for the instructor training is for the trainers to write a Data Carpentry intro for a class. Maybe you could pick a few from the instructor training classes and post them as examples for suggestions for opening for a Data Carpentry class.

**Comment by raynamharris** [comment]
I took a stab at adding the mission statement for both orgs in the intro paragraph in #788. This may or may not be what you are looking for. I did not yet at a challenge exercise.

**Comment by Valbat** [comment]
When a student takes the instructor training class, one of the exercises is to write an intro. for the data carpentry class. So, I thought the trainers could ask the students for their write ups of the introductions and if there are ones that the organization thinks rise to the top, they could post sample data carpentry introductions or templates of introductions that trainers give when starting a class that the organization would like to show case for new instructors.

**Comment by Valbat** [comment]
My response above is to clarify what I meant about the challenge. It was an exercise/challenge during the instructor training to write up an introduction covering all the points highlighted during the class for how to start a data carpentry class.

**Comment by raynamharris** [comment]
Thanks for the attempt at clarity, but I am even more confused. Is there or is there not an exercise about introducing Data Carpentry, perhaps in [this episode on introductions](https://github.com/carpentries/instructor-training/blob/gh-pages/_episodes/19-introductions.md)? 

Also, are suggestion that not only should an exercise/challenge exists but that it should be mandatory for checkout?

**Comment by Valbat** [comment]
Hi Ray: If you have time today, please call me at 617-918-1674. I think it will be easier to explain over the phone. Thank you

**Comment by karenword** [comment]
Hi @Valbat thank you for your persistence as we try to figure this out! I deleted your prior comment because I am concerned about having personal information like a phone number available in our public repository. While many things are more easily conveyed by telephone, we normally try to keep our communications about the repository here. 

My interpretation of what you're asking for is an example response for the activity in our Workshop Introductions lesson, which Rayna links to in her previous comment. I think that maybe you are using "Data Carpentry" to refer to any of our workshops, because it doesn't sound like you're looking for more background information (another kind of "introduction") about the Carpentries organizations or history. Does that sound accurate?

**Comment by karenword** [comment]
We think this issue has by other changes in the interim -- please reopen if still applicable!
