### ISSUE TITLE
improve the memory section

### ISSUE THREAD

**Issue by raynamharris** [carpentries/instructor-training#835]
As pointed out by @aurelg in #832, there is room for improving the [memory episode](https://carpentries.github.io/instructor-training/05-memory/index.html) by strengthening the connection between memory, cognition, chunking, and concept maps.   

Does anyone have comments on how they have explicitly made this connection in a workshop (e.g what language do you use to motivate this that isn't written in the lesson episode)?

**Comment by raynamharris** [comment]
Interestingly, I was reading this excellent book called [Behave](https://www.amazon.com/Behave-Biology-Humans-Best-Worst/dp/0143110918/ref=sr_1_1?s=books&ie=UTF8&qid=1543610327&sr=1-1&keywords=behave) that @karenword gave me. On page 48, there is a brief discussion of chunking and how it relates to concept maps! We might could adopt some of the language from this book to improve the lesson itself or perhaps the non-web version of the first exercise.

![img_0039](https://user-images.githubusercontent.com/7544197/49314098-fa8f9200-f4ae-11e8-8261-648fdc37778b.png)

**Comment by aurelg** [comment]
For those of us who are interested: our tendency/need/bias to infer patterns is called [pareidolia](https://en.wikipedia.org/wiki/Pareidolia). The inference of relationships between concepts (such as grouping them in chunks) can be either an [epiphany](https://en.wikipedia.org/wiki/Epiphany_(feeling)) or an [apophany](https://en.wikipedia.org/wiki/Apophenia), depending on whether this relationship is real or imaginary. The resulting mental model can consequently be either relevant or irrelevant. Since irrelevant mental models can be very hard to fix, avoiding them in the first place is important. Here comes metacognition as a very valuable skill, even though it's out of the scope of this lesson. In some "supplementary material", maybe?
