### ISSUE TITLE
Ep3: '10 words and phrases' link not available in EU

### ISSUE THREAD

**Issue by gcapes** [carpentries/instructor-training#888]
In the 'changing your language' callout, the linked page gives me this
> Unfortunately, our website is currently unavailable in most European countries. We are engaged on the issue and committed to looking at options that support our full range of digital offerings to the EU market. We continue to identify technical compliance solutions that will provide all readers with our award-winning journalism

**Comment by raynamharris** [comment]
Thanks for pointing this out @gcapes. I looked for a different source, and found this: https://open.buffer.com/motivation-words/ Does that link work for you?

**Comment by gcapes** [comment]
Yep! I guess the original was an article, but this looks to contain the key points :)

**Comment by karenword** [comment]
Nice find @raynamharris ! Same author, same content! I suggest we leave the Chicago Tribune link (and hope they get it together with the EU) but add this blog post as an alternate.

**Comment by Denubis** [comment]
https://perma.cc/LE2H-VWXG?type=image is a perma.cc record of the link, in case we want to use it or archive.org https://web.archive.org/web/20190218221337/https://www.chicagotribune.com/bluesky/hub/ct-buffer-words-and-phrases-that-motivate-bsi-hub-20160225-story.html

(Which, as a general rule, we should be using one of the two, because linkrot is an awful problem.)

**Comment by raynamharris** [comment]
Thanks @Denubis! I was looking for an internet archive version of it, but I couldn't find one. Thanks for creating these archives.
