### ISSUE TITLE
Bug in Wrap-Up-Doc PDF 

### ISSUE THREAD

**Issue by k8hertweck** [carpentries/instructor-training#999]
One of my learners (@alliblk) noted that the [Wrap-Up-Doc PDF](https://carpentries.github.io/instructor-training/files/handouts/Wrap-Up-doc.pdf) doesn't function for adding text; she will add more information below.

**Comment by sstevens2** [comment]
We also had in issue with this handout in my training today, if you write something in one box and then click on another box, it copies what you wrote into a bunch of the other boxes. 
Maybe a form where they could fill it out and then input their email address to have it send it to them might be a good solution for online trainings?

**Comment by pennyjw** [comment]
This is happening because when the form was constructed the fields were copied to make multiple blanks, so there are 5 fields called 'Text8', and text entered in one of them will be represented in them all. This can be fixed by renaming the fields so that each has a unique name in the Form fields view. These names ideally are semantic, representing what the expected content of the field is. There are also several other accessibility problems in the form.

**Comment by ChristinaLK** [comment]
Changes / updates welcome! I made the doc in a hurry for the fall lesson release. If someone knows more about creating accessible pdfs, that would be awesome.

**Comment by ChristinaLK** [comment]
@d-diaz updated version is merged. :)
